name: CI Pipeline

# Trigger the workflow on push to the develop branch
on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Node.js to install dependencies
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm install

    # Step 4: Lint TypeScript code
    - name: Lint TypeScript
      run: npm run lint

    # Step 5: Run unit tests
    - name: Run unit tests
      run: npm test

    # Step 6: Build the TypeScript project
    - name: Build TypeScript project
      run: npm run build

    # Step 7: Log in to DockerHub
    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    # Step 8: Build and push the Docker image
    - name: Build and push Docker image
      run: |
        docker build -t your-dockerhub-username/your-app-name .
        docker push your-dockerhub-username/your-app-name
